name: Python application

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest tox tox-gh-actions --no-cache-dir
        pip install -r requirements.txt --no-cache-dir

    - name: Show Python version
      run: python --version

    - name: List installed packages
      run: pip list

    - name: Test with tox
      run: tox -v

    - name: Show Tox environment info
      run: tox --version

    - name: Clean up pip cache
      run: |
        rm -rf ~/.cache/pip
