# This workflow will upload a Python Package to PyPI when a release is created.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # This is required for trusted publishing to PyPI

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build release distributions
        run: python -m build

      - name: Upload distributions for later use
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write  # Required for publishing to PyPI securely

    environment:
      name: pypi
      # Optional: uncomment and update with your PyPI project URL if you want to link it
      # url: https://pypi.org/project/YOURPROJECT/${{ github.event.release.name }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Install Twine for PyPI upload
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.0  # Pin the version of this action to ensure stability
        with:
          packages-dir: dist/
